# Spring Boot application name
spring.application.name=spring-security-practical

# PostgreSQL connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_security_postgresql
spring.datasource.username=postgres
spring.datasource.password=12345

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection pool configuration
spring.datasource.driver-class-name=org.postgresql.Driver

# to switch off the default sprig boot banner
#spring.main.banner-mode=off

spring.banner.location=classpath:banner.txt
